version: '3.8'
services:
  postgres:
    image: postgres
    container_name: snout-postgres
    ports:
      - "5432:5432"
    env_file:
      - ../src/main/resources/.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


